### ISSUE TITLE
Weird condition with some blocks

### ISSUE THREAD

**Issue by TheSnowyChickens** [Focamacho/MysticalAdaptations#10]
Hello,
I changed some blocks in your recipe config and was confused, that the seed won't show up in JEI ingame.

I don't know, what is wrong, because my thermal block entries work how they should.
Maybe it is a fail from my side, but could you give me a hint, why it is not working ? :D 

My recipe config file : 
[config file inside.zip](https://github.com/Focamacho/MysticalAdaptations/files/4081713/config.file.inside.zip)

All mods are up to date (todays date)
(mystical, mystical addon, mystical lib ,your addon, forge: 2847)
(Tinkers / Thermal / TechReborn / Mekanism / and more (I only used IDs from installed mods))

My list, which blocks don't work: (+ = I tried a new entry, - = I don't know if it work, recipe = custom recipe via crafttweaker)
silicon, +
slime, +
water, -
sulfur, (recipe)
saltpeter, (recipe)
graphite, 
titanium, 
Uran, 
AluBrass, 
KnightSlime, 
Ardite, 
Cobalt, 
Manylium, 
GrainsInfinity, 
ElectricalSteel, 
Redstone Alloy,
ConductiveIron,
Soularium,
DarkSteel,
Pulsating,
Energetic,
Vibrant,
End Steel,
Osmium,
Glowstone Ingot,
RefObbi,
Marble,
Limestone,
Basalt,
Alumite,
Yellorium,
SkyStone,
Certus,
Fluix,

**Comment by focamacho** [comment]
So the extractor works fine, but the recipes don't show up in JEI?

**Comment by TheSnowyChickens** [comment]
No, the extractor also don't work.
(I clicked with a tier 6 extractor on some blocks, which are not visible in JEI = nothing happend)
(->conclusion: only in JEI visible blocks work)

**Comment by focamacho** [comment]
I changed the init time of the Seed Extractor Recipes, maybe it can fix the issue. 
Here is:
[MysticalAdaptations-1.12.2-1.7.3.zip](https://github.com/Focamacho/MysticalAdaptations/files/4082627/MysticalAdaptations-1.12.2-1.7.3.zip)

**Comment by TheSnowyChickens** [comment]
Ah, perfect.
It work now with all seeds.

Ty for your work. :)

**Comment by focamacho** [comment]
Thanks for the report! Any problems please, create a new issue :)
I'll upload the new version to curse now.
