### ISSUE TITLE
[1.15.2] Server crashes with mod installed.

### ISSUE THREAD

**Issue by Gbergz** [Focamacho/MysticalAdaptations#12]
Title^ Crashes when mod is loaded on a server.

Mod-Version: 1.15.2-1.0.jar
MC-Version: 1.15.2
Crash-Report: https://gist.github.com/Gbergz/1beebc8e52bf53871d2eb3950514aa99

Any ideas?
- Gbergz

**Comment by focamacho** [comment]
Fixed in Mystical Adaptations 1.1
Thanks for the report!
