### ISSUE TITLE
Insanium Seed Reprocessor - No Dropped Block on Harvest

### ISSUE THREAD

**Issue by SephirothWS** [Focamacho/MysticalAdaptations#15]
A video is worth a thousand words.

https://youtu.be/gAnI5cy80YA

Minecraft 1.16.4
Forge 35.1.7
MysticalAdaptations NONE (According to in-game) (MysticalAdaptations-1.16.4-1.0.jar)

**Comment by focamacho** [comment]
Thanks for the report!
