### ISSUE TITLE
Insanium Furnace doesnt drop its Blockform when mined

### ISSUE THREAD

**Issue by Shorepion** [Focamacho/MysticalAdaptations#17]
Minecraft 1.16.4
Forge 35.1.31
MysticalAdaptations-1.16.4-1.0
(MysticalAgriculture-1.16.4-4.1.4)

https://user-images.githubusercontent.com/24994890/104831920-67cc3000-588d-11eb-8906-96a25154346e.mp4

**Comment by focamacho** [comment]
Thanks for the report!
