### ISSUE TITLE
Crash on the client side when right clicking with extractor.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Focamacho/MysticalAdaptations#2]
[crash-2019-06-23_18.03.45-client.txt](https://github.com/Focamacho/MysticalAdaptations/files/3323782/crash-2019-06-23_18.03.45-client.txt)

I right clicked using a supremium extractor and bauxite ore from pixelmon reforged.

**Comment by focamacho** [comment]
Pls, tell me if this still happen in the latest version of the mod.

**Comment by P3rf3ctXZer0** [comment]
What do you mean latest version? I am using whatever was posted in log. Crap I gave you wrong log sorry ...

**Comment by P3rf3ctXZer0** [comment]
If I find the correct one I will let you know.

**Comment by focamacho** [comment]
I has uploaded a new version of the mod today in curse:
https://www.curseforge.com/minecraft/mc-mods/mystical-adaptations/files/2730919

**Comment by P3rf3ctXZer0** [comment]
I will probably test it tomorrow.
