### ISSUE TITLE
Server crash in version 1.1.1 

### ISSUE THREAD

**Issue by CKY-** [Focamacho/MysticalAdaptations#34]
Describe the bug

server crash 

**Crash when opening seed re-processor**

**To Reproduce**

open seed re-processor with a full stack of charcoal.

**Expected behavior**

NOT crash a server 

**Screenshots / Scripts / Logs**

https://gist.github.com/CKY-/aec1d78e4874dcbdd928f733b5af4d46

**Versions:**

- Minecraft: 1.16.5
- Forge: 36.1.32
- Cucumber: 4.1.10
- Mystical Agriculture: 4.2.0
- Mystical Adaptations: 1.1.1

**Comment by focamacho** [comment]
Fixed. Thanks for the report!
