### ISSUE TITLE
Major Issues - 1.12.2 Recipe Corruptions - Make Recipe Config Seperate from Main Config for easy refresh

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Focamacho/MysticalAdaptations#4]
I mean the title says it all - the recipes corrupted and one way mods tend to fix this is have recipes separate from main config. That is even how Mystical Agriculture themselves deal with it. BlakeBr0

**Comment by focamacho** [comment]
What exactly do you mean by "Recipe Corruptions"?

**Comment by P3rf3ctXZer0** [comment]
Um after a lot of different removed mods it seems to kind of shuffle things in a way making them unusable.

On another note can an item be made into a seed? I kind of wanted to add some custom seeds.

Incase you wanted to know I already refreshed config so I cannot give you the one where recipes stopped working.

**Comment by focamacho** [comment]
Hmm.. I'll try make a better config file/a new one.
And no, a item can't be made into a seed.

**Comment by P3rf3ctXZer0** [comment]
Sorry I meant blocks - would be nice though.

**Comment by focamacho** [comment]
I think my english is not good enough to understand everything - and google translate don't help-me so much. What exactly do you means with "On another note can an item be made into a seed? I kind of wanted to add some custom seeds."?

**Comment by P3rf3ctXZer0** [comment]
So lets say a mod has a block - and I want seeds for that block - is that possible?

**Comment by focamacho** [comment]
Create new seeds? Hmm.. Unfortunately I do not know any easy way to do this.

**Comment by P3rf3ctXZer0** [comment]
What about generic seeds that inherent the texture colors of that block? So basically anything that has the .block class could be a potential seed.

Of course that block would still needed to be added to recipe table by the user.

**Comment by focamacho** [comment]
I can try make something like that, but not sure if it's possible - at least not easily.

**Comment by P3rf3ctXZer0** [comment]
Alright well I hope this helps you though :D

**Comment by focamacho** [comment]
It's been a while, but... https://www.curseforge.com/minecraft/mc-mods/mystical-creations
