### ISSUE TITLE
why is my armor taking durability it should be using supremium which is unbreakable and the tools are fine

### ISSUE THREAD

**Issue by Noahfrechette** [Focamacho/MysticalAdaptations#42]
everything but the armor is unbreakable pleas fix this problem since supremium is unbreakable this should be since it uses why is my armor taking durability it should be using supremium which is unbreakable and the tools are fine please fix

**Comment by focamacho** [comment]
Hello, supremium armor is not unbreakable, only the tools are, and Mystical Adaptations is just an addon for Mystical Agriculture, if you want supremium armor to be unbreakable you should suggest it to the main mod: https://www.curseforge.com/minecraft/mc-mods/mystical-agriculture
