### ISSUE TITLE
Insanium Watering Can grows crops slower than Supremium

### ISSUE THREAD

**Issue by dwentz89** [Focamacho/MysticalAdaptations#43]
I'm running versions MysticalAgriculture-1.12.2-1.7.5.jar and MysticalAdaptations-1.12.2-1.8.5.jar, and the Insanium Watering Can grows crops about 30% slower than the Supremium one, according to my testing.

I think the problem is the `int bonus = 4 * stack.getMetadata();` line in both versions. The Supremium one has a metadata of 4, so the bonus is 16, but the Insanium one has a metadata of 0, so the bonus is 0. I recommend changing yours to `int bonus = 4 * 5;`

**Comment by focamacho** [comment]
Thanks for pointing that!
