### ISSUE TITLE
[BUG] Insanium Seed Reprocessor - client crash

### ISSUE THREAD

**Issue by Gogo08190** [Focamacho/MysticalAdaptations#46]
Hello, 

When I shift click on the insanium reprocessor my client crashes and when I reconnect I can't see my hands anymore I have to restart the modpack to solve the problem.

Crash report : [here](https://crashy.net/RrFywzsvs8TmBlBsiqOn)

**Comment by focamacho** [comment]
Hey! What versions are you using?
From Mystical Agriculture, Mystical Adaptations and Cucumber.

**Comment by Gogo08190** [comment]
MysticalAgriculture-1.16.5-4.2.6
MysticalAdaptations-1.16.5-1.2.1
Cucumber-1.16.5-4.1.12

**Comment by focamacho** [comment]
Thanks for the report!
