### ISSUE TITLE
Insanium furnace is broken

### ISSUE THREAD

**Issue by KingToyoter** [Focamacho/MysticalAdaptations#48]
In mod version 1.18.2-1.1.1 the insanium furnace has equal fuel efficiency to vanilla furnaces

**Comment by focamacho** [comment]
Hello. The Insanium Furnace works fine for me.

I'm using:
Mystical Apdatations 1.18.2-1.1.1
Mystical Agriculture 5.1.1
Mystical Aggraditions 5.1.2
Cucumber Library 5.1.2

Can you provide more info? Maybe it is a mod conflict

**Comment by KingToyoter** [comment]
> Hello. The Insanium Furnace works fine for me.
> 
> I'm using: Mystical Apdatations 1.18.2-1.1.1 Mystical Agriculture 5.1.1 Mystical Aggraditions 5.1.2 Cucumber Library 5.1.2
> 
> Can you provide more info? Maybe it is a mod conflict

Upon my own testing using the same mod versions you have listed, I have determined that this is not caused by a mod conflict. The insanium furnace does still fucntion, just not as intended. If the item description corretcly lists the furnaces stats, then it should be 100 times faster and 10 times more fuel effient than a vanilla furnace, the cooking speed does appear to be correct, however the efficiency is not, only smelting 8 items for every coal used, rather than 80 as I assume it should be, based off of the item description.

**Comment by focamacho** [comment]
Oh I see, I was thinking about furnace speed instead of fuel efficiency, my bad.
It is fixed now, thanks for the report!
