### ISSUE TITLE
Crash - when right clicking blocks

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Focamacho/MysticalAdaptations#5]
MysticalAdaptations-1.12.2-1.4

[crash-2019-07-05_04.14.29-client.txt](https://github.com/Focamacho/MysticalAdaptations/files/3361969/crash-2019-07-05_04.14.29-client.txt)
[mysticaladaptations.txt](https://github.com/Focamacho/MysticalAdaptations/files/3361972/mysticaladaptations.txt)

**Comment by focamacho** [comment]
Which block exactly did you right-click?

**Comment by focamacho** [comment]
I think I found the problem, I'll upload a new version to curse now.
