### ISSUE TITLE
Insanium Furnace gets deleted when broken

### ISSUE THREAD

**Issue by CommanderFoxy** [Focamacho/MysticalAdaptations#55]
i dont know if this is intended or not, but, the insanium furnace gets deleted when you break it. other tiers of the furnace do not get deleted when broken.

**Comment by focamacho** [comment]
Hello! What minecraft and mod version are you playing? It seems to work for me.

**Comment by CommanderFoxy** [comment]
i am playing on 1.16.5 with mod version 1.2.2

**Comment by focamacho** [comment]
It is working fine for me. Make sure you're using the latest version of the mod (1.16.5-1.2.2)
https://www.curseforge.com/minecraft/mc-mods/mystical-adaptations/files/3706814

**Comment by CommanderFoxy** [comment]
i am currently using 1.16.5-1.2.2
![image](https://github.com/focamacho/MysticalAdaptations/assets/121730658/35fa8dfe-83f8-4b58-bd8e-094157be039c)

**Comment by focamacho** [comment]
I'm not able to replicate this :c
The furnace is working fine for me, maybe some other mod is causing this? But i'm not sure why this would happen.
