### ISSUE TITLE
Augments are missing lang descriptions (en-US)

### ISSUE THREAD

**Issue by lexifuzzpup** [Focamacho/MysticalAdaptations#58]
Augments that have been added by Mystical Adaptations do not have an implemented description and instead show as their lang id.
I have only tested this using the en-US pack and do not know if translations exist for other languages.

![image](https://github.com/focamacho/MysticalAdaptations/assets/35749102/48539b03-0d87-40b5-aa02-559ab85b864b)

**Comment by focamacho** [comment]
Descriptions added in the latest version of the mod. Thanks for the report!
