### ISSUE TITLE
Augmented armor with multiple augments only displays one augment

### ISSUE THREAD

**Issue by lexifuzzpup** [Focamacho/MysticalAdaptations#59]
When you add augments to tier 6 armor, only one of the augments is displayed in its description. For example, if I add a step assist augment and a nofall augment to a pair of insanium boots, it will only show the step assist augment as being present.

![image](https://github.com/focamacho/MysticalAdaptations/assets/35749102/c4e0fcdf-f438-4e84-aa5c-5c0cba397ef4)

**Comment by focamacho** [comment]
Fixed in the latest version. Thank you!
