### ISSUE TITLE
[1.20.1] compat with latest updates.

### ISSUE THREAD

**Issue by Bass2style** [Focamacho/MysticalAdaptations#60]
Hello,

since the last Mystical Agriculture update (7.0.7), the game is crashing when the modpack is launching.

i did a report on BlakeBr0's Git, and he pointed out that's probably caused by you mod, thing that i can confirm, it's fixed when Adaptations is disabled.

can you check about this ?

here is my report on BlakeBr0's GIT : https://github.com/BlakeBr0/MysticalAgriculture/issues/651

have a nice day.

**Comment by Maxi90909** [comment]
Can confirm this. I first thought other mods were causing this crash. But after I removed Mystical Adaptation it immediantly fixed the issue and now it no longer crashes.

**Comment by Diversion98** [comment]
I can also confirm this, @focamacho are u still developing this mod?
This issue has been open for 2 weeks now

**Comment by focamacho** [comment]
Hello! @naxakariya already made a fix for this issue (https://github.com/focamacho/MysticalAdaptations/pull/61), I'll test it and upload a new version to CurseForge/Modrinth today.
Thanks for the report!

**Comment by focamacho** [comment]
CurseForge -> https://legacy.curseforge.com/minecraft/mc-mods/mystical-adaptations/files/4955398
Modrinth -> https://modrinth.com/mod/mystical-adaptations/version/WdCcexbZ
