### ISSUE TITLE
Dragon egg seeds crash

### ISSUE THREAD

**Issue by MasterSloth1** [Focamacho/MysticalAdaptations#7]
i went to make the dragon egg seeds, right clicking the dragon egg with the seed extractor (insanium tier) makes the egg teleport away, so i shift right clicked on the egg and it crashed me

MysticalAdaptations-1.12.2-1.5.2.jar
MysticalAgriculture-1.12.2-1.7.5.jar
MysticalAgradditions-1.12.2-1.3.2.jar
Minecraft Version: - 1.12.2
forge -14.23.5.2838
crash report - https://pastebin.com/sMXCbrBq

**Comment by focamacho** [comment]
Fixed in 1.5.3.
Thanks for the report.
