### ISSUE TITLE
Crash Serverside - Something with tinkerers

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Focamacho/MysticalAdaptations#9]
https://gist.github.com/P3rf3ctXZer0/a625208062891da6a89e6e61102d4348

All information you need to fix issue is here. Including forge version etc.

**Comment by focamacho** [comment]
Oh, sorry! My mistake. Fixed in 1.7.1

**Comment by P3rf3ctXZer0** [comment]
I will test it immediately. If I have another issue - I will report it.

**Comment by TheSnowyChickens** [comment]
Hello,
I have also a crash, client side (start up): https://paste.dimdev.org/zikikateka.mccrash

**Comment by focamacho** [comment]
> Hello,
> I have also a crash, client side (start up): https://paste.dimdev.org/zikikateka.mccrash

Thanks for the report! Fixed in 1.7.2
